### ISSUE TITLE
CoC code not found in APR report

### ISSUE THREAD

**Issue by pocketfishy** [greenriver/hmis-warehouse#3707]
Hi,
I have been able to sucessfully create a data source, and upload my HMIS .zip file with no validation flags or errors. However when I go to create the APR, it can't seem to find the CoC code for my project. I have confirmed that ProjectCoC.csv exists, and was loaded into the database successfully. Any idea why this may be occuring?
Thank you,

![image](https://github.com/greenriver/hmis-warehouse/assets/110262695/214e3f3c-0d20-41fa-9d44-503234c9ab3f)

![image](https://github.com/greenriver/hmis-warehouse/assets/110262695/b5790322-1379-46f8-bdbb-ed5a40ba6b14)

projectCoC URL: http://ec2-54-202-194-225.us-west-2.compute.amazonaws.com/source_data/5?type=ProjectCoC

**Comment by eanders** [comment]
Looks like you'll need to get `rails db:seed` to work, since that populates the list of possible CoC Codes.
You may need to comment out `setup_fake_user if Rails.env.development?` in `db/seed_maker.rb` since that was having trouble.  

You might also need to run `rails grda_warehouse:daily`   That will require at least two delayed job workers to finish correctly.  (Generally that's scheduled to run each night.)
You may want

**Comment by pocketfishy** [comment]
Commenting out `setup_fake_user if Rails.env.development?` in `db/seed_maker.rb` worked! Thanks @eanders
